#! /bin/bash -e

#####################
# Configuration     #                    
#####################

TMP_DIR=tmp
OUTPUT_DIR=output

#####################
# Script            #
#####################

echo "$(ld -v)"

CMD="ct-ng build"
echo "BUILDING: ${CMD}"
${CMD}

# Prepare output
CMD="mkdir -p ${OUTPUT_DIR}"
echo "PREPARING: ${CMD}"
${CMD}

# Pack toolchain into tar archiv
CMD="tar -cjf ${OUTPUT_DIR}/$(git rev-parse --abbrev-ref HEAD)_$(date '+%Y%m%d%H%M%S')_$(git rev-parse --short HEAD)_toolchain.tar.bz2 -C ${TMP_DIR} ."
echo "PACKING: ${CMD}"
${CMD}
