#! /bin/bash -ex

#####################
# Configuration     #                    
#####################

TMP_DIR=tmp
OUTPUT_DIR=output

#####################
# Script            #
#####################

unset TARGET_ARCH
unset HOST_ARCH

ct-ng build

# Prepare output
mkdir -p ${OUTPUT_DIR}

# Pack toolchain into tar archiv
tar -cjf ${OUTPUT_DIR}/$(git rev-parse --abbrev-ref HEAD)_$(date '+%Y%m%d%H%M%S')_$(git rev-parse --short HEAD)_toolchain.tar.bz2 -C ${TMP_DIR} .

# Clean up
find -type d -exec chmod u+w {} \; 

